services:
    xpression.annotations_driver:
        class: Symftony\XpressionBundle\Annotations\Driver\AnnotationsDriver
        arguments:
            - '@annotation_reader'
            - '@xpression.expression_registry'
        tags:
            - { name: kernel.event_subscriber }

    xpression.expression_registry:
        class: Symftony\XpressionBundle\ExpressionBuilderRegistry
